import React,{useEffect,useState} from 'react';
import {ArrowDown,ArrowUp,Check,Eye,Plus,Save,Trash2,ChevronDown,ChevronUp} from 'lucide-react';
import {useLanguage} from '../../context/LanguageContext';
import {QuizConfig,QuizQuestion,QuizOption,QuizMatchField,QuizPreferences,GrindType,CoffeeRoastLevel} from '../../types';

const FIELD_OPTIONS:{key:QuizMatchField;ar:string;en:string}[]=[
 {key:'brew_method',ar:'طريقة التحضير',en:'Brew method'},
 {key:'roast_level',ar:'درجة التحميص',en:'Roast level'},
 {key:'flavor',ar:'النكهات والإيحاءات',en:'Flavor notes'},
 {key:'strength',ar:'قوة القهوة',en:'Strength'},
 {key:'acidity',ar:'الحموضة',en:'Acidity'},
 {key:'sweetness',ar:'الحلاوة',en:'Sweetness'},
 {key:'body',ar:'القوام',en:'Body'},
 {key:'balance',ar:'التوازن',en:'Balance'},
 {key:'bitterness',ar:'المرارة',en:'Bitterness'},
 {key:'caffeine',ar:'الكافيين',en:'Caffeine'}
];
const BREWS:{v:GrindType;ar:string;en:string}[]=[
 {v:'espresso',ar:'إسبريسو',en:'Espresso'},{v:'v60',ar:'V60 / فلتر',en:'V60 / Filter'},
 {v:'french_press',ar:'فرنش بريس',en:'French Press'},{v:'aeropress',ar:'أيروبريس',en:'Aeropress'},
 {v:'cold_brew',ar:'كولد برو',en:'Cold Brew'},{v:'turkish',ar:'تركية / سعودية',en:'Turkish / Saudi'}
];
const ROASTS:{v:CoffeeRoastLevel;ar:string;en:string}[]=[
 {v:'light',ar:'فاتح',en:'Light'},{v:'medium',ar:'متوسط',en:'Medium'},{v:'dark',ar:'غامق',en:'Dark'}
];
const emptyPrefs=():QuizPreferences=>({fields:[],brew_methods:[],roast_levels:[],flavors:[]});
const makeOption=(ar='',en='',icon='☕️'):QuizOption=>({id:`opt-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,label_ar:ar,label_en:en,icon,preferences:emptyPrefs()});
const makeQuestion=(i:number):QuizQuestion=>({id:`q-${Date.now()}-${i}`,title_ar:'',title_en:'',sort_order:i+1,is_enabled:true,options:[makeOption()]});
const cleanConfig=(raw:any):QuizConfig=>{
 const qs=Array.isArray(raw?.questions)?raw.questions:Array.isArray(raw)?raw:[];
 return {settings:{results_count:3,badge_ar:'مستشار القهوة',badge_en:'Coffee Finder',title_ar:'اكتشف قهوتك المثالية',title_en:'Find Your Perfect Coffee',subtitle_ar:'أجب عن الأسئلة وسنطابق تفضيلاتك مع ملف كل قهوة في المتجر.',subtitle_en:'Answer a few questions and we will match your preferences to each coffee profile.',...(raw?.settings||{})},
 questions:qs.map((q:any,i:number)=>({...q,sort_order:i+1,options:(q.options||[]).map((o:any)=>({...o,preferences:o.preferences||emptyPrefs()}))}))
 };
};
const arVal=(v:number)=>v===1?'خفيفة جداً':v===2?'خفيفة':v===3?'متوسطة':v===4?'قوية':'قوية جداً';
export default function AdminQuizManager(){
 const {t,language}=useLanguage(); const [c,setC]=useState<QuizConfig|null>(null); const [saving,setSaving]=useState(false); const [open,setOpen]=useState<number|null>(0); const [msg,setMsg]=useState('');
 useEffect(()=>{fetch('/api/admin/quiz').then(r=>r.json()).then(d=>setC(cleanConfig(d))).catch(()=>setC(cleanConfig(null)))},[]);
 if(!c)return <div className="p-10 text-center text-[#6B8C8E]">{t('جاري تحميل اختبار القهوة...','Loading Coffee Finder...')}</div>;
 const upd=(i:number,k:keyof QuizQuestion,v:any)=>{const qs=[...c.questions];qs[i]={...qs[i],[k]:v};setC({...c,questions:qs});};
 const updOpt=(qi:number,oi:number,k:keyof QuizOption,v:any)=>{const qs=[...c.questions],os=[...qs[qi].options];os[oi]={...os[oi],[k]:v};qs[qi]={...qs[qi],options:os};setC({...c,questions:qs});};
 const prefs=(qi:number,oi:number):QuizPreferences=>c.questions[qi].options[oi].preferences||emptyPrefs();
 const updPref=(qi:number,oi:number,patch:Partial<QuizPreferences>)=>updOpt(qi,oi,'preferences',{...prefs(qi,oi),...patch});
 const toggleField=(qi:number,oi:number,field:QuizMatchField)=>{const p=prefs(qi,oi);const fields=p.fields.includes(field)?p.fields.filter(x=>x!==field):[...p.fields,field];updPref(qi,oi,{fields});};
 const addQ=()=>{const q=makeQuestion(c.questions.length);setC({...c,questions:[...c.questions,q]});setOpen(c.questions.length)};
 const addOption=(qi:number)=>upd(qi,'options',[...c.questions[qi].options,makeOption()]);
 const save=async()=>{setSaving(true);setMsg('');try{const payload={...c,questions:c.questions.map((q,i)=>({...q,sort_order:i+1,options:q.options.map(o=>{const {score_rules:_legacy,...clean}=o as any;return {...clean,preferences:o.preferences||emptyPrefs()};})}))};const r=await fetch('/api/admin/quiz',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();setMsg(t('تم حفظ الاختبار بنجاح','Quiz saved successfully'));}catch{setMsg(t('تعذر حفظ الاختبار','Could not save quiz'))}finally{setSaving(false)}};
 return <div className="space-y-6" dir={language==='ar'?'rtl':'ltr'}>
  <div className="rounded-3xl bg-gradient-to-br from-[#0E5257] to-[#2B7D82] p-6 text-white flex flex-col md:flex-row gap-5 items-center"><div className="w-16 h-16 rounded-2xl bg-white/10 flex items-center justify-center text-3xl">☕</div><div className="flex-1"><div className="text-[10px] uppercase tracking-[.2em] text-white/60">Coffee Finder</div><h2 className="text-2xl font-black">{t('اختبار ترشيح القهوة','Coffee Finder Quiz')}</h2><p className="text-sm text-white/80 mt-1">{t('الأسئلة والاختيارات هنا فقط. لكل اختيار تحدد تفضيلاته من قوائم واضحة، والنظام يطابقها تلقائياً مع ملف القهوة.','Create clear customer questions and choose the preferences represented by each answer. Matching is automatic.')}</p></div><button onClick={()=>window.open('/coffee-finder','_blank')} className="px-4 py-2 rounded-xl bg-white/10 border border-white/20 text-xs font-bold flex gap-2"><Eye className="w-4 h-4"/>{t('معاينة الاختبار','Preview Quiz')}</button></div>
  {msg&&<div className="rounded-2xl bg-[#F0FAFA] border border-[#DCEBEC] p-3 text-xs font-bold flex items-center gap-2"><Check className="w-4 h-4 text-emerald-500"/>{msg}</div>}
  <section className="rounded-3xl bg-white border border-[#E8F2F2] p-5 space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-black">{t('أسئلة الاختبار','Quiz questions')}</h3><p className="text-[11px] text-[#6B8C8E]">{t('لا يوجد كود أو قواعد أو JSON. فقط سؤال، اختيارات، وتفضيلات واضحة لكل اختيار.','No code, rules, or JSON. Just questions, answers, and clear preferences.')}</p></div><button onClick={addQ} className="px-3 py-2 rounded-xl bg-[#0E5257] text-white text-xs font-bold"><Plus className="w-3 h-3 inline"/> {t('إضافة سؤال','Add question')}</button></div>
  <div className="space-y-3">{c.questions.map((q,qi)=><div key={q.id} className="rounded-2xl border border-[#E8F2F2] overflow-hidden"><div className="p-4 bg-[#F9FCFC] flex items-center gap-3"><span className="w-8 h-8 rounded-xl bg-[#E8F2F2] flex items-center justify-center font-black text-xs text-[#0E5257]">{qi+1}</span><div className="flex-1"><div className="font-bold text-sm">{q.title_ar||t('سؤال بدون عنوان','Untitled question')}</div><div className="text-[10px] text-[#6B8C8E]">{q.options.length} {t('اختيارات','answers')}</div></div><button onClick={()=>setOpen(open===qi?null:qi)} className="p-2 rounded-xl">{open===qi?<ChevronUp className="w-4 h-4"/>:<ChevronDown className="w-4 h-4"/>}</button><button onClick={()=>setC({...c,questions:c.questions.filter((_,i)=>i!==qi)})} className="p-2 text-red-500"><Trash2 className="w-4 h-4"/></button></div>
  {open===qi&&<div className="p-4 space-y-5"><div className="grid md:grid-cols-2 gap-3"><label className="text-xs font-bold">{t('السؤال بالعربي','Question in Arabic')}<input value={q.title_ar} onChange={e=>upd(qi,'title_ar',e.target.value)} className="w-full mt-1" dir="rtl"/></label><label className="text-xs font-bold">English<input value={q.title_en} onChange={e=>upd(qi,'title_en',e.target.value)} className="w-full mt-1"/></label></div><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={q.is_enabled} onChange={e=>upd(qi,'is_enabled',e.target.checked)}/>{t('السؤال ظاهر للعملاء','Show to customers')}</label>
  <div className="space-y-3">{q.options.map((o,oi)=>{const p=prefs(qi,oi);return <div key={o.id} className="rounded-2xl border border-[#E8F2F2] p-4 bg-[#FBFEFE] space-y-4"><div className="flex gap-2 items-center"><input value={o.icon||''} onChange={e=>updOpt(qi,oi,'icon',e.target.value)} className="w-12 text-center" placeholder="☕"/><input value={o.label_ar} onChange={e=>updOpt(qi,oi,'label_ar',e.target.value)} placeholder={t('نص الاختيار بالعربي','Answer in Arabic')} className="flex-1" dir="rtl"/><input value={o.label_en} onChange={e=>updOpt(qi,oi,'label_en',e.target.value)} placeholder="Answer in English" className="flex-1"/><button onClick={()=>upd(qi,'options',q.options.filter((_,i)=>i!==oi))} className="text-red-500 p-2"><Trash2 className="w-4 h-4"/></button></div>
  <div><div className="text-xs font-black mb-2">{t('هذا الاختيار يعبّر عن:','This answer represents:')}</div><div className="flex flex-wrap gap-2">{FIELD_OPTIONS.map(f=><button type="button" key={f.key} onClick={()=>toggleField(qi,oi,f.key)} className={`px-3 py-1.5 rounded-lg text-[10px] border ${p.fields.includes(f.key)?'bg-[#0E5257] text-white border-[#0E5257]':'bg-white border-[#E8F2F2]'}`}>{language==='ar'?f.ar:f.en}</button>)}</div></div>
  {p.fields.includes('brew_method')&&<div><div className="text-[10px] font-bold mb-1">{t('طرق التحضير','Brew methods')}</div><div className="flex flex-wrap gap-2">{BREWS.map(x=><button type="button" key={x.v} onClick={()=>updPref(qi,oi,{brew_methods:p.brew_methods.includes(x.v)?p.brew_methods.filter(v=>v!==x.v):[...p.brew_methods,x.v]})} className={`px-2.5 py-1 rounded-lg text-[10px] border ${p.brew_methods.includes(x.v)?'bg-[#6CC6C9] text-[#0E5257] border-[#6CC6C9]':'bg-white border-[#E8F2F2]'}`}>{language==='ar'?x.ar:x.en}</button>)}</div></div>}
  {p.fields.includes('roast_level')&&<div><div className="text-[10px] font-bold mb-1">{t('درجة التحميص','Roast level')}</div><div className="flex gap-2">{ROASTS.map(x=><button type="button" key={x.v} onClick={()=>updPref(qi,oi,{roast_levels:p.roast_levels.includes(x.v)?p.roast_levels.filter(v=>v!==x.v):[...p.roast_levels,x.v]})} className={`px-3 py-1 rounded-lg text-[10px] border ${p.roast_levels.includes(x.v)?'bg-[#6CC6C9] text-[#0E5257] border-[#6CC6C9]':'bg-white border-[#E8F2F2]'}`}>{language==='ar'?x.ar:x.en}</button>)}</div></div>}
  {p.fields.includes('flavor')&&<label className="text-[10px] font-bold">{t('النكهات المطابقة (افصل بينها بفواصل)','Matching flavor notes (comma separated)')}<input value={p.flavors.join(', ')} onChange={e=>updPref(qi,oi,{flavors:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} className="w-full mt-1" placeholder={t('مثال: شوكولاتة، كراميل، مكسرات','Example: chocolate, caramel, nuts')}/></label>}
  {(['strength','acidity','sweetness','body','balance','bitterness','caffeine'] as QuizMatchField[]).filter(f=>p.fields.includes(f)).length>0&&<div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{(['strength','acidity','sweetness','body','balance','bitterness','caffeine'] as QuizMatchField[]).filter(f=>p.fields.includes(f)).map(f=>{const val=(p as any)[f]||3;const label=FIELD_OPTIONS.find(x=>x.key===f);return <label key={f} className="text-[10px] font-bold">{language==='ar'?label?.ar:label?.en}<select value={val} onChange={e=>updPref(qi,oi,{[f]:Number(e.target.value)})} className="w-full mt-1">{[1,2,3,4,5].map(v=><option key={v} value={v}>{language==='ar'?`${v} / 5${f==='strength'?` — ${arVal(v)}`:''}`:`${v} / 5`}</option>)}</select></label>})}</div>}
  <div className="text-[9px] text-[#6B8C8E]">{p.fields.length?t('تم تحديد خصائص هذا الاختيار. النظام سيحسب درجة التطابق مع كل قهوة بناءً عليها.','Preferences selected. The engine will calculate a match score against every coffee.') :t('اختر خاصية واحدة على الأقل لهذا الاختيار ليكون له تأثير في الترشيح.','Choose at least one preference so this answer affects recommendations.')}</div>
  </div>})}</div>
  <button onClick={()=>addOption(qi)} className="text-xs font-bold text-[#0E5257]">+ {t('إضافة اختيار','Add answer')}</button>
  <div className="flex justify-between pt-2"><div className="flex gap-1"><button disabled={qi===0} onClick={()=>{const qs=[...c.questions];[qs[qi-1],qs[qi]]=[qs[qi],qs[qi-1]];setC({...c,questions:qs})}} className="p-2 rounded-lg bg-[#F0FAFA] disabled:opacity-30"><ArrowUp className="w-3 h-3"/></button><button disabled={qi===c.questions.length-1} onClick={()=>{const qs=[...c.questions];[qs[qi+1],qs[qi]]=[qs[qi],qs[qi+1]];setC({...c,questions:qs})}} className="p-2 rounded-lg bg-[#F0FAFA] disabled:opacity-30"><ArrowDown className="w-3 h-3"/></button></div></div></div>}</div>)}</div></section>
  <section className="rounded-3xl bg-white border border-[#E8F2F2] p-5 space-y-3"><h3 className="font-black">{t('شكل النتيجة','Result display')}</h3><div className="grid md:grid-cols-3 gap-3"><label className="field-label">{t('عدد المنتجات المقترحة','Products shown')}<input type="number" min="1" max="6" value={c.settings.results_count} onChange={e=>setC({...c,settings:{...c.settings,results_count:Math.max(1,Math.min(6,Number(e.target.value)))}})}/></label><label className="field-label">{t('العنوان بالعربي','Arabic title')}<input value={c.settings.title_ar} onChange={e=>setC({...c,settings:{...c.settings,title_ar:e.target.value}})} dir="rtl"/></label><label className="field-label">English title<input value={c.settings.title_en} onChange={e=>setC({...c,settings:{...c.settings,title_en:e.target.value}})}/></label></div></section>
  <div className="flex justify-end"><button onClick={save} disabled={saving} className="px-6 py-3 rounded-xl bg-[#6CC6C9] text-[#0E5257] text-xs font-black flex gap-2 items-center"><Save className="w-4 h-4"/>{saving?t('جاري الحفظ...','Saving...'):t('حفظ الاختبار','Save Quiz')}</button></div>
 </div>
}
