import React,{useEffect,useMemo,useState} from 'react';
import {useLanguage} from '../../context/LanguageContext';
import {useCurrency} from '../../context/CurrencyContext';
import {CreditCard,RefreshCw,Search,CheckCircle2,Clock3,XCircle,WalletCards} from 'lucide-react';

export default function AdminPaymentsManager(){
 const {language,t}=useLanguage(); const {formatPrice}=useCurrency(); const [orders,setOrders]=useState<any[]>([]); const [q,setQ]=useState(''); const [status,setStatus]=useState('all'); const [loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/payments');if(r.ok)setOrders(await r.json())}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>orders.filter(o=>{const s=`${o.order_number||''} ${o.customer_name||''} ${o.email||''} ${o.payment_intent_id||''}`.toLowerCase();return (!q||s.includes(q.toLowerCase()))&&(status==='all'||o.payment_status===status)}),[orders,q,status]);
 const icon=(s:string)=>s==='paid'?<CheckCircle2 className="w-4 h-4 text-emerald-500"/>:s==='failed'?<XCircle className="w-4 h-4 text-red-500"/>:<Clock3 className="w-4 h-4 text-amber-500"/>;
 return <div className="space-y-6"><div className="flex flex-col sm:flex-row justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-[#1A2E30]">{t('المدفوعات والمعاملات','Payments & Transactions')}</h1><p className="text-xs text-[#6B8C8E]">{t('كل عمليات الدفع المرتبطة بالطلبات وحالاتها ومعرفاتها','All payment transactions linked to orders, statuses and references')}</p></div><button onClick={load} className="px-4 py-2 rounded-xl bg-[#E8F2F2] font-bold flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>{t('تحديث','Refresh')}</button></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['all',t('الكل','All')],['paid',t('مدفوع','Paid')],['pending',t('معلق','Pending')],['failed',t('فشل','Failed')]].map(([v,l])=><button key={v} onClick={()=>setStatus(v)} className={`p-4 rounded-2xl border text-start ${status===v?'border-[#6CC6C9] bg-[#F0FAFA]':'border-[#E8F2F2] bg-white'}`}><div className="text-[10px] text-[#6B8C8E]">{l}</div><div className="text-xl font-extrabold">{v==='all'?orders.length:orders.filter(o=>o.payment_status===v).length}</div></button>)}</div>
 <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#6B8C8E]"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full pl-9" placeholder={t('رقم الطلب أو العميل أو معرف الدفع','Order, customer or payment ID')}/></div>
 <div className="overflow-x-auto rounded-3xl border border-[#E8F2F2] bg-white"><table className="w-full text-xs"><thead><tr className="border-b border-[#E8F2F2] text-[#6B8C8E]"><th className="p-4 text-start">{t('الطلب','Order')}</th><th className="p-4 text-start">{t('العميل','Customer')}</th><th className="p-4 text-start">{t('البوابة','Gateway')}</th><th className="p-4 text-start">{t('الحالة','Status')}</th><th className="p-4 text-start">{t('المبلغ','Amount')}</th><th className="p-4 text-start">Payment ID</th><th className="p-4 text-start">{t('التاريخ','Date')}</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} className="border-b border-[#E8F2F2]/60"><td className="p-4 font-bold">{o.order_number}</td><td className="p-4">{o.customer_name}<div className="text-[10px] text-[#6B8C8E]">{o.email}</div></td><td className="p-4 flex items-center gap-2"><WalletCards className="w-4 h-4 text-[#0E5257]"/>{o.payment_method}</td><td className="p-4 flex items-center gap-2">{icon(o.payment_status)}{o.payment_status}</td><td className="p-4 font-bold">{formatPrice(o.total_amount)}</td><td className="p-4 font-mono text-[10px] max-w-56 truncate">{o.payment_intent_id||'—'}</td><td className="p-4">{o.created_at?new Date(o.created_at).toLocaleString(language==='ar'?'ar-SA':'en-SA'):''}</td></tr>)}</tbody></table></div></div>
}
